/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_haswalk_jblas_JBlas */

#ifndef _Included_com_haswalk_jblas_JBlas
#define _Included_com_haswalk_jblas_JBlas
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    daxpy
 * Signature: (ID[DI[DI)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jblas_JBlas_daxpy
  (JNIEnv *, jclass, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    ddot
 * Signature: (I[DI[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_ddot
  (JNIEnv *, jclass, jint, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dnrm2
 * Signature: (I[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_dnrm2
  (JNIEnv *, jclass, jint, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dasum
 * Signature: (I[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_dasum
  (JNIEnv *, jclass, jint, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dgemv
 * Signature: (IIIID[DI[DID[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_dgemv
  (JNIEnv *, jclass, jint, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dsyr
 * Signature: (IIID[DI[DI)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_dsyr
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dspr
 * Signature: (IIID[DI[D)D
 */
JNIEXPORT jdouble JNICALL Java_com_haswalk_jblas_JBlas_dspr
  (JNIEnv *, jclass, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dgemm
 * Signature: (IIIIIID[DI[DID[DI)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jblas_JBlas_dgemm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jint);

/*
 * Class:     com_haswalk_jblas_JBlas
 * Method:    dsymm
 * Signature: (IIIIID[DI[DID[DI)V
 */
JNIEXPORT void JNICALL Java_com_haswalk_jblas_JBlas_dsymm
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jdouble, jdoubleArray, jint, jdoubleArray, jint, jdouble, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
